[package]
name = "server_frontend"
version = "0.1.0"
edition = "2021"
authors = ["陈功 <chengong456@qq.com>"]

[dependencies]
hyper = "0.14.27" 
tokio = { version = "1.34.0", features = ["full"] }
routerify = "3.0.0"
thiserror = "1.0.40"
clap = { version = "4.4.6", features = ["derive"] }


